/**
 * @file StatechartSignals.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * and contains an enumerated type listing all signals referenced by 
 * the following state machines:
 *
 * Test5, Test9, Test9_1, Test7, Test2, Test4, Test6, Test8, Test3, Test1
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _StatechartSignals_h
#define _StatechartSignals_h

enum StatechartSignals
{
   /* "During" signal */
   DURING = Q_USER_SIG,

   /* User defined signals */
   Ev1,  /* 0x05 */
   Ev2,  /* 0x06 */
   Ev3,  /* 0x07 */

   /* Timer Events */
   T8S1_timerEv,   /* 0x08 */
   T8S2_timerEv,   /* 0x09 */
   T8S21_timerEv,  /* 0x0A */
   T8S22_timerEv,  /* 0x0B */

   /* Maximum signal id */
   MAX_SIG
};

#endif /* _StatechartSignals_h */
