/**
 * @file Test7.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test7_h
#define _test7_h

#include "qf_port.h"
#include "qassert.h"

#include "Test7Impl.h"

enum StateEnumTest7
{
   TEST7_T7S1,       /* State = 0 */
   TEST7_T7S2,       /* State = 1 */
   TEST7_T7S2_T7S21, /* State = 2 */
   TEST7_T7S2_T7S22  /* State = 3 */
};


typedef struct Test7
{
   QActive super_;
   char objName[256];
   Test7Impl* impl;

   enum StateEnumTest7 mystate;
} Test7;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test7* Test7_Constructor(Test7* me, char* objNameNew, Test7Impl* implPtr);
void Test7_initial(Test7* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T7S1
 */

QSTATE Test7_T7S1(Test7* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T7S2
 *    T7S21
 *    T7S22
 */

QSTATE Test7_T7S2(Test7* me, QEvent const* e);
QSTATE Test7_T7S2_T7S21(Test7* me, QEvent const* e);
QSTATE Test7_T7S2_T7S22(Test7* me, QEvent const* e);

#endif /* _test7_h */
