/**
 * @file Test4.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test4_h
#define _test4_h

#include "qf_port.h"
#include "qassert.h"

#include "Test4Impl.h"

enum StateEnumTest4
{
   TEST4_T4S1,               /* State = 0 */
   TEST4_T4S2,               /* State = 1 */
   TEST4_T4S2_REGION1,       /* State = 2 */
   TEST4_T4S2_REGION1_T4S21, /* State = 3 */
   TEST4_T4S2_REGION1_T4S22, /* State = 4 */
   TEST4_T4S2_REGION2,       /* State = 5 */
   TEST4_T4S2_REGION2_T4S23, /* State = 6 */
   TEST4_T4S2_REGION2_T4S24  /* State = 7 */
};


/* Declaration of Local Concurrent Regions
 *
 * These regions are present in this
 * state machine
 */
typedef struct Test4T4S2Region1Region
{
   QHsm super_;
   QActive * parent;
   char objName[256];
   Test4Impl* impl;

   enum StateEnumTest4 mystate;
} Test4T4S2Region1Region;


typedef struct Test4T4S2Region2Region
{
   QHsm super_;
   QActive * parent;
   char objName[256];
   Test4Impl* impl;

   enum StateEnumTest4 mystate;
} Test4T4S2Region2Region;



typedef struct Test4
{
   QActive super_;
   char objName[256];
   Test4Impl* impl;

   /* Concurrent State Regions */
   struct Test4T4S2Region1Region *region1;
   struct Test4T4S2Region2Region *region2;

   enum StateEnumTest4 mystate;
} Test4;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test4* Test4_Constructor(Test4* me, char* objNameNew, Test4Impl* implPtr);
void Test4_initial(Test4* me, QEvent const* e);

/***
 * Subregion prototypes for Region1
 */
Test4T4S2Region1Region *
Test4T4S2Region1Region_Constructor(Test4T4S2Region1Region* me, char* objNameNew, Test4Impl* implPtr, QActive * parent);

void 
Test4T4S2Region1Region_initial(Test4T4S2Region1Region* me, QEvent const* e);


/***
 * Subregion prototypes for Region2
 */
Test4T4S2Region2Region *
Test4T4S2Region2Region_Constructor(Test4T4S2Region2Region* me, char* objNameNew, Test4Impl* implPtr, QActive * parent);

void 
Test4T4S2Region2Region_initial(Test4T4S2Region2Region* me, QEvent const* e);


/**
 * Function prototypes for state handlers
 *
 * T4S2
 *    Region1 [Orthogonal Region]
 *       T4S21
 *       T4S22
 *    Region2 [Orthogonal Region]
 *       T4S23
 *       T4S24
 */

QSTATE Test4_T4S2(Test4* me, QEvent const* e);
QSTATE Test4_T4S2_Region1_T4S21(Test4T4S2Region1Region* me, QEvent const* e);
QSTATE Test4_T4S2_Region1_T4S22(Test4T4S2Region1Region* me, QEvent const* e);
QSTATE Test4_T4S2_Region2_T4S23(Test4T4S2Region2Region* me, QEvent const* e);
QSTATE Test4_T4S2_Region2_T4S24(Test4T4S2Region2Region* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T4S1
 */

QSTATE Test4_T4S1(Test4* me, QEvent const* e);

#endif /* _test4_h */
