/**
 * @file Test7.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test7.h"
#include "log_event.h"


Test7* Test7_Constructor(Test7* me, char* objNameNew, Test7Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test7_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test7");
   me->impl = implPtr;

   return me;
}

void Test7_initial(Test7* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev2);
   QActive_subscribe_(& me->super_, Ev1);

   Q_INIT(Test7_T7S1);
}

/**
 * Implementation of T7S1
 */
QSTATE Test7_T7S1(Test7* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T7S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST7_T7S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test7_T7S2);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test7_T7S2_T7S22);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T7S2
 */
QSTATE Test7_T7S2(Test7* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T7S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST7_T7S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Q_INIT_SIG:
      Q_INIT(Test7_T7S2_T7S21);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test7_T7S1);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T7S21
 */
QSTATE Test7_T7S2_T7S21(Test7* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T7S21");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST7_T7S2_T7S21;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test7_T7S1);
      return 0;
   }
   return (QSTATE) Test7_T7S2;
}

/**
 * Implementation of T7S22
 */
QSTATE Test7_T7S2_T7S22(Test7* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T7S22");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST7_T7S2_T7S22;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;
   }
   return (QSTATE) Test7_T7S2;
}

