/**
 * @file Test9.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test9.h"
#include "log_event.h"


Test9* Test9_Constructor(Test9* me, char* objNameNew, Test9Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test9_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test9");
   me->impl = implPtr;

   return me;
}

void Test9_initial(Test9* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev2);
   QActive_subscribe_(& me->super_, Ev1);

   Q_INIT(Test9_T9S1);
}

/**
 * Implementation of T9S1
 */
QSTATE Test9_T9S1(Test9* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T9S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST9_T9S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      QF_publish( Q_NEW(QEvent, Ev2) );
      Q_TRAN(Test9_T9S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T9S2
 */
QSTATE Test9_T9S2(Test9* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T9S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST9_T9S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test9_T9S1);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

