/**
 * @file Test9_1.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test9_1.h"
#include "log_event.h"


Test9_1* Test9_1_Constructor(Test9_1* me, char* objNameNew, Test9_1Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test9_1_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test9_1");
   me->impl = implPtr;

   return me;
}

void Test9_1_initial(Test9_1* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev2);

   Q_INIT(Test9_1_T9_1S1);
}

/**
 * Implementation of T9_1S1
 */
QSTATE Test9_1_T9_1S1(Test9_1* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T9_1S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST9_1_T9_1S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test9_1_T9_1S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T9_1S2
 */
QSTATE Test9_1_T9_1S2(Test9_1* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T9_1S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST9_1_T9_1S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test9_1_T9_1S1);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

