/**
 * @file Test6.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test6.h"
#include "log_event.h"


Test6* Test6_Constructor(Test6* me, char* objNameNew, Test6Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test6_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test6");
   me->impl = implPtr;

   return me;
}

void Test6_initial(Test6* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev2);
   QActive_subscribe_(& me->super_, Ev1);
   QActive_subscribe_(& me->super_, Ev3);

   Q_INIT(Test6_T6S1);
}

/**
 * Implementation of T6S1
 */
QSTATE Test6_T6S1(Test6* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T6S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST6_T6S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test6_T6S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T6S2
 */
QSTATE Test6_T6S2(Test6* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T6S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST6_T6S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test6_T6S1);
      return 0;

     case Ev3:
      strcat(stateName, " Ev3");
      LogEvent_log(stateName);
      Q_TRAN(Test6_T6S2);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test6_T6S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

