/**
 * @file Test8.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test8.h"
#include "log_event.h"


Test8* Test8_Constructor(Test8* me, char* objNameNew, Test8Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test8_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test8");
   me->impl = implPtr;

   /***
    * Initialize all the timers
    *
    * Each timer object is declared only once, within
    * the top-level state chaning or an orthogonal
    * region.  The top-level state captures each timer
    * event and passes it to the proper state machine.
    */

   /* Top-Level Timers */
   QTimeEvt_ctor(&(me->T8S1_timer), T8S1_timerEv);
   QTimeEvt_ctor(&(me->T8S22_timer), T8S22_timerEv);
   QTimeEvt_ctor(&(me->T8S2_timer), T8S2_timerEv);
   QTimeEvt_ctor(&(me->T8S21_timer), T8S21_timerEv);

   return me;
}

void Test8_initial(Test8* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev1);

   Q_INIT(Test8_T8S1);
}

/**
 * Implementation of T8S1
 */
QSTATE Test8_T8S1(Test8* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T8S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST8_T8S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      QTimeEvt_postIn(&me->T8S1_timer, (QActive *) me, 1);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      QTimeEvt_disarm(&me->T8S1_timer);
      return 0;

     case T8S1_timerEv:
      strcat(stateName, " T8S1_timerEv");
      LogEvent_log(stateName);
      Q_TRAN(Test8_T8S2);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test8_T8S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T8S2
 */
QSTATE Test8_T8S2(Test8* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T8S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST8_T8S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      QTimeEvt_postIn(&me->T8S2_timer, (QActive *) me, 5);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      QTimeEvt_disarm(&me->T8S2_timer);
      return 0;

     case T8S2_timerEv:
      strcat(stateName, " T8S2_timerEv");
      LogEvent_log(stateName);
      Q_TRAN(Test8_T8S1);
      return 0;

     case Q_INIT_SIG:
      Q_INIT(Test8_T8S2_T8S21);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test8_T8S1);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T8S21
 */
QSTATE Test8_T8S2_T8S21(Test8* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T8S21");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST8_T8S2_T8S21;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      QTimeEvt_postIn(&me->T8S21_timer, (QActive *) me, 3);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      QTimeEvt_disarm(&me->T8S21_timer);
      return 0;

     case T8S21_timerEv:
      strcat(stateName, " T8S21_timerEv");
      LogEvent_log(stateName);
      Q_TRAN(Test8_T8S2_T8S22);
      return 0;
   }
   return (QSTATE) Test8_T8S2;
}

/**
 * Implementation of T8S22
 */
QSTATE Test8_T8S2_T8S22(Test8* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T8S22");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST8_T8S2_T8S22;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      QTimeEvt_postIn(&me->T8S22_timer, (QActive *) me, 1);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      QTimeEvt_disarm(&me->T8S22_timer);
      return 0;

     case T8S22_timerEv:
      strcat(stateName, " T8S22_timerEv");
      LogEvent_log(stateName);
      Q_TRAN(Test8_T8S2_T8S21);
      return 0;
   }
   return (QSTATE) Test8_T8S2;
}

