/**
 * @file Test1.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test1.h"
#include "log_event.h"


Test1* Test1_Constructor(Test1* me, char* objNameNew, Test1Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test1_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test1");
   me->impl = implPtr;

   return me;
}

void Test1_initial(Test1* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev1);

   Q_INIT(Test1_S1);
}

/**
 * Implementation of S1
 */
QSTATE Test1_S1(Test1* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST1_S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test1_S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of S2
 */
QSTATE Test1_S2(Test1* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST1_S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test1_S1);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

