/**
 * @file Test1.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test1_h
#define _test1_h

#include "qf_port.h"
#include "qassert.h"

#include "Test1Impl.h"

enum StateEnumTest1
{
   TEST1_S1, /* State = 0 */
   TEST1_S2  /* State = 1 */
};


typedef struct Test1
{
   QActive super_;
   char objName[256];
   Test1Impl* impl;

   enum StateEnumTest1 mystate;
} Test1;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test1* Test1_Constructor(Test1* me, char* objNameNew, Test1Impl* implPtr);
void Test1_initial(Test1* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * S2
 */

QSTATE Test1_S2(Test1* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * S1
 */

QSTATE Test1_S1(Test1* me, QEvent const* e);

#endif /* _test1_h */
