/**
 * @file Test9_1.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test9_1_h
#define _test9_1_h

#include "qf_port.h"
#include "qassert.h"

#include "Test9_1Impl.h"

enum StateEnumTest9_1
{
   TEST9_1_T9_1S1, /* State = 0 */
   TEST9_1_T9_1S2  /* State = 1 */
};


typedef struct Test9_1
{
   QActive super_;
   char objName[256];
   Test9_1Impl* impl;

   enum StateEnumTest9_1 mystate;
} Test9_1;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test9_1* Test9_1_Constructor(Test9_1* me, char* objNameNew, Test9_1Impl* implPtr);
void Test9_1_initial(Test9_1* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T9_1S1
 */

QSTATE Test9_1_T9_1S1(Test9_1* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T9_1S2
 */

QSTATE Test9_1_T9_1S2(Test9_1* me, QEvent const* e);

#endif /* _test9_1_h */
