/**
 * @file Test3.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test3.h"
#include "log_event.h"


Test3* Test3_Constructor(Test3* me, char* objNameNew, Test3Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test3_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test3");
   me->impl = implPtr;

   /***
    * Initialize the deep histories 
    */
   me->myT3S2history = NULL;

   return me;
}

void Test3_initial(Test3* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev2);
   QActive_subscribe_(& me->super_, Ev1);
   QActive_subscribe_(& me->super_, Ev3);

   Q_INIT(Test3_T3S1);
}

/**
 * Implementation of T3S1
 */
QSTATE Test3_T3S1(Test3* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T3S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST3_T3S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test3_T3S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T3S2
 */
QSTATE Test3_T3S2(Test3* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T3S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST3_T3S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      me->myT3S2history = QHsm_getState_(&(me->super_.super_) );
      return 0;

     case Q_INIT_SIG:
      Q_INIT(Test3_T3S2_T3S21);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test3_T3S1);
      return 0;

     case Ev3:
      strcat(stateName, " Ev3");
      LogEvent_log(stateName);
      Q_TRAN(Test3_T3S3);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T3S21
 */
QSTATE Test3_T3S2_T3S21(Test3* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T3S21");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST3_T3S2_T3S21;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test3_T3S2_T3S22);
      return 0;
   }
   return (QSTATE) Test3_T3S2;
}

/**
 * Implementation of T3S22
 */
QSTATE Test3_T3S2_T3S22(Test3* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T3S22");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST3_T3S2_T3S22;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test3_T3S2_T3S21);
      return 0;
   }
   return (QSTATE) Test3_T3S2;
}

/**
 * Implementation of T3S3
 */
QSTATE Test3_T3S3(Test3* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T3S3");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST3_T3S3;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev3:
      strcat(stateName, " Ev3");
      LogEvent_log(stateName);
      if(me->myT3S2history == NULL)
      {
         Q_TRAN(Test3_T3S2_T3S21);
      }
      else{
         Q_TRAN_DYN(me->myT3S2history);
      }
      return 0;
   }
   return (QSTATE) QHsm_top;
}

