/**
 * @file Test9.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test9_h
#define _test9_h

#include "qf_port.h"
#include "qassert.h"

#include "Test9Impl.h"

enum StateEnumTest9
{
   TEST9_T9S1, /* State = 0 */
   TEST9_T9S2  /* State = 1 */
};


typedef struct Test9
{
   QActive super_;
   char objName[256];
   Test9Impl* impl;

   enum StateEnumTest9 mystate;
} Test9;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test9* Test9_Constructor(Test9* me, char* objNameNew, Test9Impl* implPtr);
void Test9_initial(Test9* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T9S1
 */

QSTATE Test9_T9S1(Test9* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T9S2
 */

QSTATE Test9_T9S2(Test9* me, QEvent const* e);

#endif /* _test9_h */
