/**
 * @file Test3.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test3_h
#define _test3_h

#include "qf_port.h"
#include "qassert.h"

#include "Test3Impl.h"

enum StateEnumTest3
{
   TEST3_T3S1,       /* State = 0 */
   TEST3_T3S2,       /* State = 1 */
   TEST3_T3S2_T3S21, /* State = 2 */
   TEST3_T3S2_T3S22, /* State = 3 */
   TEST3_T3S3        /* State = 4 */
};


typedef struct Test3
{
   QActive super_;
   char objName[256];
   Test3Impl* impl;

   /* Histories */
   QState myT3S2history;

   enum StateEnumTest3 mystate;
} Test3;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test3* Test3_Constructor(Test3* me, char* objNameNew, Test3Impl* implPtr);
void Test3_initial(Test3* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T3S3
 */

QSTATE Test3_T3S3(Test3* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T3S1
 */

QSTATE Test3_T3S1(Test3* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T3S2
 *    T3S21
 *    T3S22
 */

QSTATE Test3_T3S2(Test3* me, QEvent const* e);
QSTATE Test3_T3S2_T3S21(Test3* me, QEvent const* e);
QSTATE Test3_T3S2_T3S22(Test3* me, QEvent const* e);

#endif /* _test3_h */
