/**
 * @file Test4.c
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */


#include <stdlib.h>
#include <string.h>
#include "qep_port.h"
#include "qassert.h"
#include "StatechartSignals.h"
#include "Test4.h"
#include "log_event.h"


Test4* Test4_Constructor(Test4* me, char* objNameNew, Test4Impl* implPtr)
{
   QActive_ctor_(&me->super_, (QState)Test4_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Test4");
   me->impl = implPtr;

   /***
    * Allocate and initialize the orthogonal region machines
    */
   me->region1 = (Test4T4S2Region1Region *) malloc( sizeof( Test4T4S2Region1Region ));
   Test4T4S2Region1Region_Constructor( me->region1, objNameNew, implPtr, &me->super_);
   me->region2 = (Test4T4S2Region2Region *) malloc( sizeof( Test4T4S2Region2Region ));
   Test4T4S2Region2Region_Constructor( me->region2, objNameNew, implPtr, &me->super_);

   return me;
}

void Test4_initial(Test4* me,  QEvent const *e)
{
   QActive_subscribe_(& me->super_, Ev2);
   QActive_subscribe_(& me->super_, Ev1);
   QActive_subscribe_(& me->super_, Ev3);

   /***
    * Initiate the orthogonal regions
    */
   QHsm_init( &(me->region1->super_), e );
   QHsm_init( &(me->region2->super_), e );

   Q_INIT(Test4_T4S1);
}

/**
 * Implementation of T4S1
 */
QSTATE Test4_T4S1(Test4* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T4S1");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST4_T4S1;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test4_T4S2);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T4S2
 */
QSTATE Test4_T4S2(Test4* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T4S2");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST4_T4S2;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      QHsm_dispatch( &(me->region1->super_),  e);
      QHsm_dispatch( &(me->region2->super_),  e);
      return 0;

     case Ev1:
      strcat(stateName, " Ev1");
      LogEvent_log(stateName);
      Q_TRAN(Test4_T4S1);
      return 0;

     /**
      * Dispatch transition events to orthogonal regions
      */
     case Ev2:
     case Ev3:
      QHsm_dispatch( &(me->region2->super_), e);
      QHsm_dispatch( &(me->region1->super_), e);
      return 0;
   }
   return (QSTATE) QHsm_top;
}


Test4T4S2Region1Region *
Test4T4S2Region1Region_Constructor(Test4T4S2Region1Region *me, char* objNameNew, Test4Impl* implPtr, QActive* parent)
{
   QHsm_ctor_(&me->super_, (QState)Test4T4S2Region1Region_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Region1");
   me->impl = implPtr;
   me->parent = parent;
   return me;
}

void 
Test4T4S2Region1Region_initial(Test4T4S2Region1Region *me,  QEvent const* e)
{
   Q_INIT(&Test4_T4S2_Region1_T4S21);
}

/**
 * Implementation of T4S21
 */
QSTATE Test4_T4S2_Region1_T4S21(Test4T4S2Region1Region* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T4S21");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST4_T4S2_REGION1_T4S21;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test4_T4S2_Region1_T4S22);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T4S22
 */
QSTATE Test4_T4S2_Region1_T4S22(Test4T4S2Region1Region* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T4S22");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST4_T4S2_REGION1_T4S22;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev2:
      strcat(stateName, " Ev2");
      LogEvent_log(stateName);
      Q_TRAN(Test4_T4S2_Region1_T4S21);
      return 0;
   }
   return (QSTATE) QHsm_top;
}


Test4T4S2Region2Region *
Test4T4S2Region2Region_Constructor(Test4T4S2Region2Region *me, char* objNameNew, Test4Impl* implPtr, QActive* parent)
{
   QHsm_ctor_(&me->super_, (QState)Test4T4S2Region2Region_initial);
   strcpy(me->objName, objNameNew);
   strcat(me->objName, " Region2");
   me->impl = implPtr;
   me->parent = parent;
   return me;
}

void 
Test4T4S2Region2Region_initial(Test4T4S2Region2Region *me,  QEvent const* e)
{
   Q_INIT(&Test4_T4S2_Region2_T4S23);
}

/**
 * Implementation of T4S23
 */
QSTATE Test4_T4S2_Region2_T4S23(Test4T4S2Region2Region* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T4S23");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST4_T4S2_REGION2_T4S23;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev3:
      strcat(stateName, " Ev3");
      LogEvent_log(stateName);
      Q_TRAN(Test4_T4S2_Region2_T4S24);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

/**
 * Implementation of T4S24
 */
QSTATE Test4_T4S2_Region2_T4S24(Test4T4S2Region2Region* me, QEvent const *e)
{
   char stateName[256];

   strcpy(stateName, me->objName);
   strcat(stateName, "T4S24");

   switch (e->sig)
   {
     case Q_ENTRY_SIG:
      me->mystate = TEST4_T4S2_REGION2_T4S24;
      strcat(stateName, " ENTRY");
      LogEvent_log(stateName);
      return 0;

     case Q_EXIT_SIG:
      strcat(stateName, " EXIT");
      LogEvent_log(stateName);
      return 0;

     case Ev3:
      strcat(stateName, " Ev3");
      LogEvent_log(stateName);
      Q_TRAN(Test4_T4S2_Region2_T4S23);
      return 0;
   }
   return (QSTATE) QHsm_top;
}

