/**
 * @file Test6.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test6_h
#define _test6_h

#include "qf_port.h"
#include "qassert.h"

#include "Test6Impl.h"

enum StateEnumTest6
{
   TEST6_T6S1, /* State = 0 */
   TEST6_T6S2  /* State = 1 */
};


typedef struct Test6
{
   QActive super_;
   char objName[256];
   Test6Impl* impl;

   enum StateEnumTest6 mystate;
} Test6;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test6* Test6_Constructor(Test6* me, char* objNameNew, Test6Impl* implPtr);
void Test6_initial(Test6* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T6S1
 */

QSTATE Test6_T6S1(Test6* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T6S2
 */

QSTATE Test6_T6S2(Test6* me, QEvent const* e);

#endif /* _test6_h */
