/**
 * @file Test8.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test8_h
#define _test8_h

#include "qf_port.h"
#include "qassert.h"

#include "Test8Impl.h"

enum StateEnumTest8
{
   TEST8_T8S1,       /* State = 0 */
   TEST8_T8S2,       /* State = 1 */
   TEST8_T8S2_T8S21, /* State = 2 */
   TEST8_T8S2_T8S22  /* State = 3 */
};


typedef struct Test8
{
   QActive super_;
   char objName[256];
   Test8Impl* impl;

   /* Timers */
   QTimeEvt T8S1_timer;
   QTimeEvt T8S22_timer;
   QTimeEvt T8S2_timer;
   QTimeEvt T8S21_timer;

   enum StateEnumTest8 mystate;
} Test8;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test8* Test8_Constructor(Test8* me, char* objNameNew, Test8Impl* implPtr);
void Test8_initial(Test8* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T8S1
 */

QSTATE Test8_T8S1(Test8* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T8S2
 *    T8S21
 *    T8S22
 */

QSTATE Test8_T8S2(Test8* me, QEvent const* e);
QSTATE Test8_T8S2_T8S21(Test8* me, QEvent const* e);
QSTATE Test8_T8S2_T8S22(Test8* me, QEvent const* e);

#endif /* _test8_h */
