/**
 * @file Test2.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test2_h
#define _test2_h

#include "qf_port.h"
#include "qassert.h"

#include "Test2Impl.h"

enum StateEnumTest2
{
   TEST2_T2S1,       /* State = 0 */
   TEST2_T2S2,       /* State = 1 */
   TEST2_T2S2_T2S21, /* State = 2 */
   TEST2_T2S2_T2S22  /* State = 3 */
};


typedef struct Test2
{
   QActive super_;
   char objName[256];
   Test2Impl* impl;

   enum StateEnumTest2 mystate;
} Test2;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test2* Test2_Constructor(Test2* me, char* objNameNew, Test2Impl* implPtr);
void Test2_initial(Test2* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T2S1
 */

QSTATE Test2_T2S1(Test2* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T2S2
 *    T2S21
 *    T2S22
 */

QSTATE Test2_T2S2(Test2* me, QEvent const* e);
QSTATE Test2_T2S2_T2S21(Test2* me, QEvent const* e);
QSTATE Test2_T2S2_T2S22(Test2* me, QEvent const* e);

#endif /* _test2_h */
