/**
 * @file Test5.h
 *
 * This file was generated by the SIM MagicDraw statechart converter,
 * which converts MagicDraw statecharts expressed in XML to Miro Samek's
 * C Quantum Framework.
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _test5_h
#define _test5_h

#include "qf_port.h"
#include "qassert.h"

#include "Test5Impl.h"

enum StateEnumTest5
{
   TEST5_T5S1, /* State = 0 */
   TEST5_T5S2  /* State = 1 */
};


typedef struct Test5
{
   QActive super_;
   char objName[256];
   Test5Impl* impl;

   enum StateEnumTest5 mystate;
} Test5;


/**
 * Function prototypes for state machine creation and
 * initialization.
 */

Test5* Test5_Constructor(Test5* me, char* objNameNew, Test5Impl* implPtr);
void Test5_initial(Test5* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T5S2
 */

QSTATE Test5_T5S2(Test5* me, QEvent const* e);

/**
 * Function prototypes for state handlers
 *
 * T5S1
 */

QSTATE Test5_T5S1(Test5* me, QEvent const* e);

#endif /* _test5_h */
