/**
 * @file StatechartSignals.h
 *
 * This file was generated by the StateChart Autocoder and contains an
 * enumerated type listing all signals referenced by the following state machines:
 *
 * DoEx
 *
 * &copy; 2009 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _StatechartSignals_h
#define _StatechartSignals_h

enum StatechartSignals {
   /* "During" signal */
   DURING = Q_USER_SIG,

   /* User defined signals */
   Ev1,      /* 0x0005 */

   /* Maximum signal id */
   MAX_SIG
};

#endif /* _StatechartSignals_h */
