/**
 * @file StatechartSignals.h
 *
 * This file was generated by the StateChart Autocoder and contains an
 * enumerated type listing all signals referenced by the following state machines:
 *
 * Sequencer
 *
 * &copy; 2009-2010 Jet Propulsion Lab / California Institute of Technology
 */

#ifndef _StatechartSignals_h
#define _StatechartSignals_h

enum StatechartSignals {
    /* "During" signal */
    DURING = Q_USER_SIG,

    /* User defined signals */
    Error,                  /* 0x0005 */
    Event0,                 /* 0x0006 */
    Event1,                 /* 0x0007 */
    Event2,                 /* 0x0008 */
    EventN,                 /* 0x0009 */
    Recover,                /* 0x000A */
    RepeatAction,           /* 0x000B */
    Reset,                  /* 0x000C */

    /* Maximum signal id */
    MAX_SIG
};

#endif /* _StatechartSignals_h */
