/**
 * @file StatechartSignals.h
 *
 * Autocode command line: -c -sm Simple1 ../Simple.mdxml
 *
 * This file was generated by the StateChart Autocoder and contains an
 * enumerated type listing signals belonging to the following state machines:
 *
 * Simple1
 *
 * &copy; 2009-2016 Jet Propulsion Lab / California Institute of Technology
 */
#ifndef STATECHARTSIGNALS_H_
#define STATECHARTSIGNALS_H_

enum StatechartSignals {
    /* "During" signal */
    DURING = Q_USER_SIG,

    /* User defined signals */
    EV1_SIG,/* 0x0005 */

    /* Maximum signal id */
    Q_BAIL_SIG = 0x7FFFFFF-1 /* Internal: terminate region/submachine */,
    MAX_SIG    = 0x7FFFFFF   /* Last possible ID! */
};

/**
 * Completion Event used to signal completion of, and thus enable exiting
 * out of, Composite and SubMachine States.  For Submachine State, event carries
 * the ID of instance -- enum value of containing substate -- that terminated.
 * If applicable, Substate event also carries exit point used.
 * 
 * Making this a C Union ensures that just enough memory is allocated to
 * contain the largest event type.
 */
typedef union {
    struct {
        QEvent super;  // C-style inheritance: QEvent is base type
        int32_t substate;   // containing substate for Submachine completion
        int32_t exitPoint;  // exitPoint used to exit Submachine, if applicable
    } completion_evt;

    QEvent base_evt;  // Mission-defined base event
} QCompletionEvt;

#endif /* STATECHARTSIGNALS_H_ */
